"""empty message

Revision ID: b07c18b37501
Revises: 439d1e6892c1
Create Date: 2017-06-12 23:03:45.247341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b07c18b37501'
down_revision = '439d1e6892c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
